### PR TITLE
Add Zerotier One Quadlet

### PR DESCRIPTION
**Pull request by UnusualNorm**
Hey there! I was looking to upload some of my Quadlet files here, however, I have no idea what style y'all like! I tried my best to guess what structure the project is going to follow, so please tell me if anything should be changed.

### CODE REVIEW

**Comment by UnusualNorm** [comment]
Currently unable to sign until I get my git environment set up.

**Comment by rhatdan** [comment]
Could you add a README.md file in the newly created directory to explain your example quadlet.

**Comment by rhatdan** [comment]
I think this quadlet must be run as root, so that should be explained within the README.md file.

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
